name: ACE
channels: 
  - nodefaults
  - conda-forge
  - bioconda
dependencies:
  - numpy
  - scipy
  - pandas
  - pyyaml
  - jupyter
  - notebook
  - seaborn 
  - matplotlib
  - libopenblas
  - snakemake
  - snakemake-executor-plugin-slurm
  - snakefmt
  - hdf5
  - pyarrow
  - numba
  - pip
  - pip:
    - pypair
    - -e .
 