name: ACE
channels: 
  - nodefaults
  - conda-forge
  - bioconda
dependencies:
  - numpy
  - scipy
  - pandas
  - pyyaml
  - jupyter
  - notebook
  - seaborn
  - matplotlib
  - pillow
  - libopenblas
  - snakemake
  - snakemake-executor-plugin-slurm
  - snakefmt
  - pyarrow
  - numba
  - pytest
  - ruff
  - pip
  # optional: for generating methods.pdf
  # - pandoc
  # - tectonic
  - pip:
    - -e .
variables:
  MPLBACKEND: Agg
 