# ACE Simulation Configuration
# Default values are used unless overridden in a scenario

defaults:
  seed: 42
  A: 0.5
  C: 0.2
  N: 100000
  ngen: 3
  fam_size: 2.7
  p_mztwin: 0.02
  p_nonsocial_father: 0.10

scenarios:
  baseline10K:
    N: 10000

  baseline100K: {}

  baseline1M:
    N: 1000000

  high_heritability:
    A: 0.8
    C: 0.0


  low_heritability:
    A: 0.1
    C: 0.0

  small_test:
    seed: 123
    N: 10000
