no_twins:
  seed: 14042
  pedigree:
    p_mztwin: 0
assortative_mating:
  seed: 80042
  pedigree:
    assort1: 0.3
    assort2: 0.0
assortative_mating_both:
  seed: 81042
  N: 100000
  pedigree:
    assort1: 0.3
    assort2: 0.15
high_mating_lambda:
  seed: 15042
  pedigree:
    mating_lambda: 3.0
