high_heritability:
  seed: 4042
  pedigree:
    trait1:
      A: 0.8
      C: 0.0
      E: 0.2
    trait2:
      A: 0.8
      C: 0.0
      E: 0.2
low_heritability:
  seed: 5042
  pedigree:
    trait1:
      A: 0.1
      C: 0.1
      E: 0.8
    trait2:
      A: 0.1
      C: 0.1
      E: 0.8
no_heritability:
  seed: 6042
  pedigree:
    trait1:
      A: 0
      C: 0
      E: 1.0
    trait2:
      A: 0
      C: 0
      E: 1.0
