tetra_test:
  seed: 9042
  censoring:
    max_age: 200
    gen_censoring:
      0:
      - 0
      - 200
      1:
      - 0
      - 200
      2:
      - 0
      - 200
      3:
      - 0
      - 200
  phenotype:
    trait1:
      beta: 20
    trait2:
      beta: 20
beta_2:
  seed: 10042
  phenotype:
    trait1:
      beta: 2.0
    trait2:
      beta: 2.0
beta_4:
  seed: 11042
  phenotype:
    trait1:
      beta: 4.0
    trait2:
      beta: 4.0
beta_sex:
  seed: 22042
  phenotype:
    trait1:
      beta_sex: 0.5
    trait2:
      beta_sex: 0.5
lognormal_phenotype:
  seed: 17042
  phenotype:
    trait1:
      beta: 1.0
      model: frailty
      params:
        distribution: lognormal
        mu: 4.0
        sigma: 0.8
    trait2:
      beta: 1.5
      model: frailty
      params:
        distribution: lognormal
        mu: 3.5
        sigma: 0.6
gamma_phenotype:
  seed: 18042
  phenotype:
    trait1:
      beta: 1.0
      model: frailty
      params:
        distribution: gamma
        shape: 2.0
        scale: 1000.0
    trait2:
      beta: 1.5
      model: frailty
      params:
        distribution: gamma
        shape: 3.0
        scale: 500.0
loglogistic_phenotype:
  seed: 19042
  phenotype:
    trait1:
      beta: 1.0
      model: frailty
      params:
        distribution: loglogistic
        scale: 60.0
        shape: 4.0
    trait2:
      beta: 1.5
      model: frailty
      params:
        distribution: loglogistic
        scale: 40.0
        shape: 3.0
gompertz_phenotype:
  seed: 20042
  phenotype:
    trait1:
      beta: 1.0
      model: frailty
      params:
        distribution: gompertz
        rate: 0.0001
        gamma: 0.05
    trait2:
      beta: 1.5
      model: frailty
      params:
        distribution: gompertz
        rate: 0.0003
        gamma: 0.07
mixed_hazard:
  seed: 21042
  phenotype:
    trait1:
      beta: 1.0
      model: frailty
      params:
        distribution: loglogistic
        scale: 4
        shape: 3.5
    trait2:
      beta: 1.5
      model: frailty
      params:
        distribution: lognormal
        mu: 4.16
        sigma: 0.076
increasing_prevalence:
  seed: 16042
  G_pheno: 4
  phenotype:
    trait1:
      prevalence:
        2: 0.03
        3: 0.05
        4: 0.08
        5: 0.12
    trait2:
      prevalence:
        2: 0.03
        3: 0.05
        4: 0.08
        5: 0.12
