adult_ltm:
  seed: 23042
  N: 50000
  phenotype:
    trait1:
      model: adult
      prevalence: 0.1
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.2
    trait2:
      model: adult
      prevalence: 0.2
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.2
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.3
    rC: 0.0
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  censoring:
    gen_censoring:
      0:
      - 0
      - 80
adult_cox:
  seed: 24042
  N: 50000
  phenotype:
    trait1:
      model: adult
      prevalence: 0.1
      params:
        method: cox
        cip_x0: 50
        cip_k: 0.2
    trait2:
      model: adult
      prevalence: 0.2
      params:
        method: cox
        cip_x0: 50
        cip_k: 0.2
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.3
    rC: 0.0
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  censoring:
    gen_censoring:
      0:
      - 0
      - 80
adult_ltm_sex_prev:
  seed: 25042
  N: 5000
  phenotype:
    trait1:
      model: adult
      prevalence:
        female: 0.08
        male: 0.12
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.2
    trait2:
      model: adult
      prevalence:
        female: 0.1
        male: 0.2
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.2
first_passage:
  seed: 26042
  N: 50000
  phenotype:
    trait1:
      model: first_passage
      params:
        drift: -0.01
        shape: 100
      beta: 1.0
    trait2:
      model: first_passage
      params:
        drift: -0.005
        shape: 80
      beta: 1.5
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.3
    rC: 0.0
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  censoring:
    gen_censoring:
      0:
      - 0
      - 80
first_passage_cure:
  seed: 27042
  N: 50000
  phenotype:
    trait1:
      model: first_passage
      params:
        drift: 0.05
        shape: 100
      beta: 1.0
    trait2:
      model: first_passage
      params:
        drift: 0.02
        shape: 80
      beta: 1.5
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.3
    rC: 0.0
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  censoring:
    gen_censoring:
      0:
      - 0
      - 80
