adult_ltm_test:
  seed: 23042
  N: 50000
  phenotype_model1: adult_ltm
  phenotype_model2: adult_ltm
  prevalence1: 0.1
  prevalence2: 0.2
  phenotype_params1:
    cip_x0: 50
    cip_k: 0.2
  phenotype_params2:
    cip_x0: 50
    cip_k: 0.2
  C1: 0.0
  E1: 0.5
  C2: 0.0
  E2: 0.5
  rA: 0.3
  rC: 0.0
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  gen_censoring:
    0:
    - 0
    - 80
adult_cox_test:
  seed: 24042
  N: 50000
  phenotype_model1: adult_cox
  phenotype_model2: adult_cox
  prevalence1: 0.1
  prevalence2: 0.2
  phenotype_params1:
    cip_x0: 50
    cip_k: 0.2
  phenotype_params2:
    cip_x0: 50
    cip_k: 0.2
  C1: 0.0
  E1: 0.5
  C2: 0.0
  E2: 0.5
  rA: 0.3
  rC: 0.0
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  gen_censoring:
    0:
    - 0
    - 80
adult_ltm_sex_prev:
  seed: 25042
  N: 5000
  phenotype_model1: adult_ltm
  phenotype_model2: adult_ltm
  prevalence1:
    female: 0.08
    male: 0.12
  prevalence2:
    female: 0.1
    male: 0.2
  phenotype_params1:
    cip_x0: 50
    cip_k: 0.2
  phenotype_params2:
    cip_x0: 50
    cip_k: 0.2
first_passage_test:
  seed: 26042
  N: 50000
  phenotype_model1: first_passage
  phenotype_model2: first_passage
  phenotype_params1:
    drift: -0.01
    shape: 100
  phenotype_params2:
    drift: -0.005
    shape: 80
  beta1: 1.0
  beta2: 1.5
  C1: 0.0
  E1: 0.5
  C2: 0.0
  E2: 0.5
  rA: 0.3
  rC: 0.0
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  gen_censoring:
    0:
    - 0
    - 80
first_passage_cure_test:
  seed: 27042
  N: 50000
  phenotype_model1: first_passage
  phenotype_model2: first_passage
  phenotype_params1:
    drift: 0.05
    shape: 100
  phenotype_params2:
    drift: 0.02
    shape: 80
  beta1: 1.0
  beta2: 1.5
  C1: 0.0
  E1: 0.5
  C2: 0.0
  E2: 0.5
  rA: 0.3
  rC: 0.0
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  gen_censoring:
    0:
    - 0
    - 80
small_test:
  seed: 12042
  N: 1000
