"""Emit `config/epimight_onset_censoring.yaml` — the onset × censoring × prevalence
EPIMIGHT h²-bias study.

A controlled factorial study of how EPIMIGHT's liability-scale h² estimate
degrades as a function of median age-of-onset and degree of (right-)censoring,
holding heritability fixed (A=0.5, h²_liability=0.5) over 10-generation
pedigrees.

Grid (4 × 4 × 4 = 64 cells):
  * prevalence K  ∈ {0.01, 0.05, 0.25, 0.50}   (pinned lifetime K via the LTM
                                                 liability threshold; see ADR 0005)
  * median onset  cip_x0 ∈ {8, 16, 32, 64}     (logistic-CIF midpoint; cip_k fixed)
  * censoring     window right-edge ∈ {10, 20, 40, 80}

Censoring is the observation window [0, edge] applied UNIFORMLY to all 10
generations (left fixed at 0; smaller edge = heavier right-censoring) — a single
unambiguous "degree of censoring" knob, deliberately not neurodev's progressive
calendar-time schedule. Competing-risk death is a constant realistic Weibull
mortality on every cell.

Run from the simACE repo root:
    python scripts/generate_onset_censoring_sweep.py
which overwrites `config/epimight_onset_censoring.yaml`.
"""

from __future__ import annotations

from pathlib import Path

import yaml

# --- factorial grid ----------------------------------------------------------

K_LEVELS = [0.01, 0.05, 0.25, 0.50]
CIP_X0_LEVELS = [8, 16, 32, 64]
EDGE_LEVELS = [10, 20, 40, 80]

# --- fixed parameters --------------------------------------------------------

N = 250_000
G_SIM = 12
G_PED = 10
G_PHENO = 10
REPLICATES = 1
CIP_K = 0.15

# Liability ACE: heritability fixed at 0.5 in every cell.
A, C, E = 0.5, 0.0, 0.5

# Constant realistic competing-risk mortality (matches epimight_bias "death").
DEATH_SCALE = 164
DEATH_RHO = 2.73

SEED_BASE = 60_000

OUT_PATH = Path("config/epimight_onset_censoring.yaml")

HEADER = """# epimight_onset_censoring — EPIMIGHT h²-bias surface study.
#
# Generated by scripts/generate_onset_censoring_sweep.py. **Do not hand-edit.**
# Re-run the helper to regenerate.
#
# Factorial 4×4×4 = 64 cells:
#   prevalence K  ∈ {0.01, 0.05, 0.25, 0.50}   (pinned lifetime K, LTM threshold)
#   median onset  cip_x0 ∈ {8, 16, 32, 64}     (cip_k fixed at 0.15)
#   censor edge   right-edge ∈ {10, 20, 40, 80} (window [0, edge], all 10 gens)
#
# Heritability is fixed (A=0.5 → h²_liability=0.5) so the only swept axes are
# onset, censoring intensity, and prevalence. The latent-K vs observed-prevalence
# divergence under censoring (ADR 0005) is the bias mechanism under study.
"""


class _FlowDict(dict):
    """A dict subclass PyYAML renders inline (flow style) — for gen_censoring."""


def _flow_dict_representer(dumper, data):
    return dumper.represent_mapping("tag:yaml.org,2002:map", data, flow_style=True)


class _FlowList(list):
    """A list subclass PyYAML renders inline (flow style) — for [lo, hi] windows."""


def _flow_list_representer(dumper, data):
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=True)


yaml.SafeDumper.add_representer(_FlowDict, _flow_dict_representer)
yaml.SafeDumper.add_representer(_FlowList, _flow_list_representer)


def scenario_name(k: float, x0: int, edge: int) -> str:
    """e.g. eoc_K01_x08_c10 for K=0.01, cip_x0=8, edge=10."""
    return f"eoc_K{int(round(k * 100)):02d}_x{x0:02d}_c{edge:02d}"


def _trait_block(k: float, x0: int) -> dict:
    return {
        "model": "adult",
        "params": {
            "method": "ltm",
            "cip_x0": x0,
            "cip_k": CIP_K,
            "prevalence": k,
        },
    }


def build_scenario(seed: int, k: float, x0: int, edge: int) -> dict:
    gen_censoring = _FlowDict({g: _FlowList([0, edge]) for g in range(G_PED)})
    return {
        "seed": seed,
        "N": N,
        "G_sim": G_SIM,
        "G_ped": G_PED,
        "G_pheno": G_PHENO,
        "replicates": REPLICATES,
        "pedigree": {
            "p_mztwin": 0,
            "trait1": {"A": A, "C": C, "E": E},
            "trait2": {"A": A, "C": C, "E": E},
            "rA": 0.0,
            "rC": 0.0,
        },
        "phenotype": {
            "trait1": _trait_block(k, x0),
            "trait2": _trait_block(k, x0),
        },
        "censoring": {
            "gen_censoring": gen_censoring,
            "death_scale": DEATH_SCALE,
            "death_rho": DEATH_RHO,
        },
    }


def build_scenarios() -> dict:
    scenarios: dict[str, dict] = {}
    idx = 0
    for k in K_LEVELS:
        for x0 in CIP_X0_LEVELS:
            for edge in EDGE_LEVELS:
                name = scenario_name(k, x0, edge)
                scenarios[name] = build_scenario(SEED_BASE + idx, k, x0, edge)
                idx += 1
    return scenarios


def main() -> None:
    scenarios = build_scenarios()
    text = HEADER + "\n" + yaml.safe_dump(
        scenarios, sort_keys=False, default_flow_style=False, width=1000
    )
    OUT_PATH.write_text(text)
    print(f"Wrote {len(scenarios)} scenarios → {OUT_PATH} ({OUT_PATH.stat().st_size:,} bytes)")

    # Sanity-check by loading via simACE's resolver.
    from simace.config import resolve_defaults, resolve_scenarios

    d = resolve_defaults(Path("config"))
    s = resolve_scenarios(Path("config"), defaults=d)
    folder = [k for k in s if s[k].get("folder") == "epimight_onset_censoring"]
    print(f"Resolver loaded {len(folder)} epimight_onset_censoring scenarios")


if __name__ == "__main__":
    main()
